### ISSUE TITLE
how to run it?

### ISSUE THREAD

**Issue by Valtsu0** [carykh/evolutionSteer#16] opened 2017-08-22 11:47 UTC
someone tell what i need to run it or what

**Comment by BurgerLord** [comment] 2017-08-22 14:28
Yeah I don't know either.

**Comment by cade1236** [comment] 2017-09-20 14:13
how do you get it to run??????

**Comment by MauroMombelli** [comment] 2017-09-20 20:30
download the zip file, decompress it in the processing project folder
(sketchbook in your home folder), remove the "-master" from the folder
name, and you are ready to go (processing 2.x)

2017-09-20 16:15 GMT+02:00 cade1236 <notifications@github.com>:

**Comment by MauroMombelli** [comment] 2017-09-20 21:46
plase close as duplicate of #15

**Comment by GJComedian** [comment] 2017-09-27 12:48
What's processing project folder? @MauroMombelli

**Comment by MauroMombelli** [comment] 2017-09-27 13:46
Please read the manual of processing at processing.org, there you will find
much better explanation and example than what can be done in this issue.

Also when doing informatics related stuff, before making a question, search
it on your favorite search engine.

**Comment by ProjectHSI** [comment] 2020-05-16 09:45
Compile the files in Processing Version 2. Then run. [Pressing the Play button in Processing V2 Should do them both.]

**Closed as completed** 2020-05-17 12:00 UTC
